### ISSUE TITLE
Proposal: Get the number of total result for a search

### ISSUE THREAD

**Issue by Jonatanmdez** [serp-spider/search-engine-google#1]
In the top of the query, you can see: 
About 119,000,000 results (0.68 seconds) 

I think is very import to know the number of total indexed elements.

**Comment by gsouf** [comment]
Agreed, but that should be done with care, because the number format is different according to the language.

For instance in english we got ``58,900,000``

```html
<div id="resultStats">
    About 58,900,000 results
    <nobr> (0.68 seconds)&nbsp;</nobr>
</div>
```


But in french we got ``52 000 000``

```html
<div id="resultStats">
    Environ 52&nbsp;000&nbsp;000&nbsp;résultats
    <nobr> (0,70&nbsp;secondes)&nbsp;</nobr>
</div>
```

Do you think it is useful to get it as an interger, or as a string as returned by google?

**Comment by Jonatanmdez** [comment]
I think is better the integer, in my case of example I only need the number.

Maybe another solution can be make a method for get the Dom and each user can parse aditional data.

**Comment by gsouf** [comment]
As mentioned in #2 it's available but not documented yet, I opened serp-spider/documentation#2 for this.

By the way parsing the number as an integer should not be so hard!

**Comment by gsouf** [comment]
@Jonatanmdez it's now available and that's documented just here: 
https://serp-spider.github.io/documentation/search-engine/google/parse-page/#number-of-results

**Comment by Jonatanmdez** [comment]
Thanks !!

Amazing :+1:
