### ISSUE TITLE
Manually resolve a captcha req

### ISSUE THREAD

**Issue by itroteam** [serp-spider/search-engine-google#102]
Hi! first of all thank for this interesting work.
I'm trying to get a workaround for reCaptcha. It could be acceptable to manually solve it.
I've tried that solution but is not working:
- i am using it with ajax: for any key into a text form (key1,key2,key3......) i'm doing an ajax request to your library
- Getting the captcha url from GoogleCaptchaException->getCaptcha()->getErrorPage()->getUrl()
- getting back the url as an <a target="_blank">
- click on it to manually solve the captcha
Simply resolving the captcha in a new tab is not working, it seems that the detection is not only IP based but also cookie based...
Any ideas?
Thank you!

**Comment by gsouf** [comment]
Hi @itroteam 

Solving captca manually is a good idea, but it was abandonned when google started to use recaptcha v2. That's too much efforts. 

We have other plans: to provide better support for headless browsers ; it should make proxies living longer and also it will allow to implement better captcha solving management.

That said. If you still want to solve captcha manually then you should indeed take cookies in account and feed serps cookies jar with the cookies that fixed the captcha. It contains a specific cookie that will allow you to bypass captchas for a certain amount of time. You can find how to play with cookies just here: [https://serp-spider.github.io/documentation/cookies/}(https://serp-spider.github.io/documentation/cookies/).

I'm closing the issue but if you want to provide some feedback or have further questions, feel free to comment or to re-open it.
