### ISSUE TITLE
Faking location with &gs_l=

### ISSUE THREAD

**Issue by LunarDevelopment** [serp-spider/search-engine-google#103]
`https://www.google.com/search?ei=N949W4T-FMKegAbkvrGIDQ&q=seo&oq=seo&gs_l=psy-ab.3..35i39k1j0i131i67k1j0i67k1l6j0i7i30k1j0i67k1.3416.3416.0.3713.1.1.0.0.0.0.78.78.1.1.0....0...1.1.64.psy-ab..0.1.78....0.Q133s747Kik` 

The above is a search query which Google Chrome has included a geolocation parameter with, does anyone have experience in using this with SERP SPIDER to fake a location during searches ?

**Comment by gsouf** [comment]
Hi @LunarDevelopment What is your actual issue with this?

**Comment by LunarDevelopment** [comment]
Just a question / discussion, not an issue. 

Though if it's possible to fake locations using search params like the above or even "near=location" then it could be a feature request I suppose.

**Comment by gsouf** [comment]
I'm not using fake location, but as far as I know I think that now google gives more importance to your ip location instead of the params in the url.

**Comment by LunarDevelopment** [comment]
Seems pretty close to faking location by setting gs_l param (unfortunately you need to get your hands on a string from the location you want to fake) 

Easy to set : 
`$url->setParam('gs_l', 'psy-ab.3...blah.blah.blah');`
