### ISSUE TITLE
How to use NaturalResults Parser with Google SERP scraped with Curl

### ISSUE THREAD

**Issue by puneetas3** [serp-spider/search-engine-google#107]
I am scraping Google search with another script/code as a curl request (its integrated with proxies, UA etc). How can I feed the response of curl request (google.com search page) to NaturalResults for further processing?

Is there a method to use string (curl response) with getNaturalResults(); Thanks.

**Comment by gsouf** [comment]
Hi @puneetas3 

You can do the following:

```php
$urlOfTheGooglePage = GoogleUrl::fromString('http://google.com/search?q=.....');
$htlmOfTheGooglePageYouParsed = '<html>.......';

$serp = new GoogleSerp($htlmOfTheGooglePageYouParsed, $urlOfTheGooglePage);
```
