### ISSUE TITLE
Can't install through composer

### ISSUE THREAD

**Issue by ShinJii89** [serp-spider/search-engine-google#108]
Hi,

I can't install newest (0.4.2) version through composer...

> sudo composer require --prefer-dist 'serps/search-engine-google'
Using version ^0.4.2 for serps/search-engine-google
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.
Problem 1
The requested package serps/search-engine-google No version set (parsed as 1.0.0) could not be found.
Problem 2
Installation request for serps/search-engine-google ^0.4.2 -> satisfiable by serps/search-engine-google[v0.4.2].
serps/cli v1.1.0 requires serps/search-engine-google ~0.3.0 -> satisfiable by serps/search-engine-google[0.3.0.x-dev].
Can only install one of: serps/search-engine-google[v0.4.2, 0.3.0.x-dev].
Installation request for serps/cli ^1.1 -> satisfiable by serps/cli[v1.1.0].

Any suggestions?

**Comment by gsouf** [comment]
Hi @ShinJii89 

Thanks for reporting there was an issue with the cli package, that should be fixed now
