### ISSUE TITLE
DOM Change (Cannot parse a classical result.)

### ISSUE THREAD

**Issue by dennisoderwald** [serp-spider/search-engine-google#110]
> Cannot parse a classical result. Google DOM has possibly changed and an update may be required.

[mobile-device-management.html.zip](https://github.com/serp-spider/search-engine-google/files/2386168/65b6be0a-7619-4018-97c9-989cdec53319.html.zip)

**Comment by gsouf** [comment]
Hi @dennisoderwald Thanks for reporting, can you confirm that this is fixed by version ``0.4.3``?

**Comment by dennisoderwald** [comment]
Hi @gsouf,

@msiemens is one of our developers. He tested directly with the attached HTML and also added a test to the pull request.

So the problem is solved.
