### ISSUE TITLE
Issue with description field in news

### ISSUE THREAD

**Issue by sameerpanjwani** [serp-spider/search-engine-google#15]
When trying to access the `$result->cards[0]->description`, it returns an error `ErrorException in InTheNews.php line 60:
Trying to get property of non-object`.

This seems to be because description doesn't exist for the news item in the search result. If doesn't exist, should return blank instead.

**Comment by gsouf** [comment]
I will do the necessary to fix it

**Comment by gsouf** [comment]
@sameerpanjwani please can you tell me if it's ok now ?

**Comment by sameerpanjwani** [comment]
We're getting news results, no issues
