### ISSUE TITLE
Answer box being detected as "classical_video"

### ISSUE THREAD

**Issue by sameerpanjwani** [serp-spider/search-engine-google#20]
For example, search "what is php", the first result is an answer result (perhaps can be called "classical_answer") but you've detected as "classical_video"

**Comment by gsouf** [comment]
@sameerpanjwani that was fixed in the previous commit, documentation needs to be written, I tag it as "needs review", let me know if everything is good to you

**Comment by gsouf** [comment]
@sameerpanjwani do you think that answer box results should be an extension of classical results? 

The reason I ask the question is that they share exactly the same items (title, description, url, destination)

**Comment by gsouf** [comment]
Doc available here https://serp-spider.github.io/documentation/search-engine/google/parse-page/#answer-box
