### ISSUE TITLE
Wrong parameters for exception RequestErrorException in GoogleClient.php 110

### ISSUE THREAD

**Issue by RubtsovAV** [serp-spider/search-engine-google#22]
PHP Fatal error:  Wrong parameters for Exception([string $exception [, long $code [, Exception $previous = NULL]]]) in /vendor/serps/search-engine-google/src/GoogleClient.php on line 110

               $errorDom = new GoogleError($response->getPageContent(), $effectiveUrl);

                if ($errorDom->isCaptcha()) {
                    throw new GoogleCaptchaException(new GoogleCaptcha($errorDom));
                } else {
                    throw new RequestErrorException($errorDom);
                }

`$errorDom` must be a string

**Comment by RubtsovAV** [comment]
I made fix for that https://github.com/serp-spider/search-engine-google/pull/23 .

**Comment by gsouf** [comment]
Fixed by 6cf4c7b
