### ISSUE TITLE
Classical recipe results with a thumb are detected as video results

### ISSUE THREAD

**Issue by gsouf** [serp-spider/search-engine-google#24]
The result in the screen shot is detected as a video result
![screenshot from 2016-05-31 09 23 29](https://cloud.githubusercontent.com/assets/3215399/15666539/906fe7d4-2711-11e6-8606-0894bf1df9dd.png)

They should be implemented as classical result ( + recipe ?)

**Comment by sameerpanjwani** [comment]
Classical Result + Schema  (or Classical + Structured)

https://support.bigcommerce.com/articles/Public/How-can-I-use-microdata-to-improve-my-search-results

**Comment by gsouf** [comment]
There is no standard way to detect that this is a recipe result, but we can detect it as structured result. @sameerpanjwani what do you think about "CLASSICAL_ILLUSTRATED" for the name? I think that "CLASSICAL_STRUCTURED" might lead to confusion.

 Hopefully we can still make the difference between video results and other results and video results (even small ones), they will still be available under  the name ``CLASSICAL_VIDEO``.

It's already available with the last commit @sameerpanjwani please feel free to give me your feedback

What changed: 
The data ``videoCover`` will be renamed with the name ``thumb`` to be generic to all illustrated results (that includes recipes and videos)

**Comment by gsouf** [comment]
Documentation todo

**Comment by sameerpanjwani** [comment]
I think this is fine, CLASSICAL_ILLUSTRATED sounds good enough to me

**Comment by gsouf** [comment]
Documentated: https://serp-spider.github.io/documentation/search-engine/google/parse-page/#classical-illustrated
