### ISSUE TITLE
Local (MAP) results are not coming

### ISSUE THREAD

**Issue by lmahesh5** [serp-spider/search-engine-google#28]
This is the url i am trying to parse : https://www.google.co.in/search?q=chennai+schools&uule=w+CAIQICIHQ2hlbm5haQ&gws_rd=cr

It has contain local (map) results.
But i am able to get only classical results from this through parser, MAP results are not coming.

I tried with different keywords and in that news, images, videos are all captured, but MAP is not coming in the result.

**Comment by gsouf** [comment]
Checking this soon

**Comment by gsouf** [comment]
Fixed in #30
