### ISSUE TITLE
Brand pack is coming under classical

### ISSUE THREAD

**Issue by lmahesh5** [serp-spider/search-engine-google#31]
http://serp-spider.github.io/documentation/search-engine/google/parse-page/#classical-large

As mentioned above, the brand pack is not coming under "classical large" section, it is coming under "classical" only but sub-links array is available.
Please check

**Comment by gsouf** [comment]
Hi @lmahesh5 

I dont have this issue. I tried by searching "github" (https://www.google.fr/search?q=github&gws_rd=cr&ei=JG7OV4qsKsq1aYmYguAB) and I'm getting this as the first result:

```json
   {
      "url": "https://github.com/",
      "title": "How people build software · GitHub",
      "types": [
        "classical",
        "classical_large"
      ]
    }
````
with both of "classical" and "classical large".

Can you give me an example that fails please ?

**Comment by lmahesh5** [comment]
https://www.mondovo.io/files/serp-test/2016-08-31/88441-1.html

Please check this result, when we parse this, the first result type coming as classical.

**Comment by gsouf** [comment]
That's weird, I'm getting this:

```json
       {
            "types": [
                "classical",
                "classical_large"
            ],
            "title": "Surreal CMS",
            "url": "https:\/\/www.surrealcms.com\/"
        }
```

Are you using the last version with unmodified sources ?

**Comment by gsouf** [comment]
Did you pay attention that ``$result->getTypes()``  will return an array with all the types (in this case "classical" and "classical_large"

**Comment by lmahesh5** [comment]
Sorry, that is the mistake.
I am taking the first value from the array and so getting only classical.
Thanks.

**Comment by gsouf** [comment]
Good!
