### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by dsslimshaddy** [serp-spider/search-engine-google#37]
problem while installing using composer

  Problem 1
    - Can only install one of: psr/http-message[1.0, 1.0.1].
    - Can only install one of: psr/http-message[1.0.1, 1.0].
    - Can only install one of: psr/http-message[1.0, 1.0.1].
    - serps/core 0.1.0 requires psr/http-message 1.0 -> satisfiable by psr/http-message[1.0].
    - serps/http-client-curl v0.1.0 requires serps/core ~0.1.0 -> satisfiable by serps/core[0.1.0].
    - Installation request for serps/http-client-curl ^0.1.0 -> satisfiable by serps/http-client-curl[v0.1.0].
    - Installation request for psr/http-message == 1.0.1.0 -> satisfiable by psr/http-message[1.0.1].

Installation failed, reverting ./composer.json to its original content.

**Comment by gsouf** [comment]
Can you show me the content of the ``require`` and ``require-dev`` sections of your ``composer.json please`` ?

**Comment by dsslimshaddy** [comment]
This is my **composer.json** on ubuntu 15.xx
{
    "require": {
        "giggsey/libphonenumber-for-php": "^7.4",
        "phpmailer/phpmailer": "^5.2",
        "jwilsson/spotify-web-api-php": "^1.3",
        "foolz/sphinxql-query-builder": "^1.0",
        "google/apiclient":"^2.0",
        "serps/http-client-curl":"^0.1.0"
       }
}

**Note: ** When i installed this composer.json on fresh installation of windows it ran without any problem.

**Comment by gsouf** [comment]
I just published an update in the core (v0.1.1), can you try ``composer update`` please?

**Comment by dsslimshaddy** [comment]
Wonderful works like a charm. Out of curiosity what was the bug and what did you do to fix it ?

**Comment by gsouf** [comment]
In the composer.json of the repository serps/core [I replaced the version ``1.0`` with ``^1.0.0``](https://github.com/serp-spider/core/commit/2123619e20b518bbf8aebee0ef01220b875436d2)

Then it makes it available to install every 1.x version of the package ``psr/http-message``

**Comment by dsslimshaddy** [comment]
Oh yeah . That was a good bug
