### ISSUE TITLE
Image base64 is showing some invalid image

### ISSUE THREAD

**Issue by dsslimshaddy** [serp-spider/search-engine-google#43]
Using documentation getting image_group `$image->image` gives invalid image code below

data:image/gif;base64,R0lGODlhAQABAIAAAP///////yH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==

Fix it

**Comment by gsouf** [comment]
In the version 0.1.0 image data are returned as given by google as stated in the doc the image might be "either an image url or a base64 encoded image". The image you get is not invalide, it's a base64 encoded image.

In version 0.2 the image data will be easier to parse, minor info available in #35
