### ISSUE TITLE
Google parser stop working.

### ISSUE THREAD

**Issue by fissben** [serp-spider/search-engine-google#45]
Hello, yesterday I noticed that parser is broken now. I suggest it comes with google update. Can anyone check it ?

**Comment by fissben** [comment]
This morning script fails with following exception: "Unable to check javascript status. Google DOM has possibly changed and an update may be required". But now it works fine. 
Maybe google is testing something? Did someone catch same exception's last 24 hours?

**Comment by gsouf** [comment]
Hi @fissben maybe are you encountering the google test cards as described in #38 

It's implemented in the last dev version, but not released as stable yet. 

The next time it happens, you might catch the exception and save the dom in a file to see how the dom looks like

**Comment by fissben** [comment]
Here are back up of response I have met. 
[untitled.txt](https://github.com/serp-spider/search-engine-google/files/552596/untitled.txt)

**Comment by gsouf** [comment]
@fissben thanks, that's helpful to find the issue.

Do you have the exact exception trace? It would be very helpful to know what method part of the parser failed to parse.
