### ISSUE TITLE
Implement large classical result

### ISSUE THREAD

**Issue by gsouf** [serp-spider/search-engine-google#5]
When a site has sitelinks, it is detected a map result, large classical result should be used instead

**Comment by gsouf** [comment]
Partial support implemented in cbbc654cc6232251294ac0c04ceed9ba06f39273

- Sitelinks are not parsed yet
- documentation needs to be updated

**Comment by andreasanta** [comment]
Thanks @gsouf. This is a partial fix for me, since results coming in the "srg" div are not being caught. Please see #6 for further improvement (tested against non working result-sets).

**Comment by gsouf** [comment]
Documenation updated at https://serp-spider.github.io/documentation/search-engine/google/parse-page/#classical-large
