### ISSUE TITLE
Get results from HTML file

### ISSUE THREAD

**Issue by gayathriw** [serp-spider/search-engine-google#53]
Is it possible to get the results from a saved copy of google search results HTML file (not fetched with this scraper)?

**Comment by gsouf** [comment]
Hi @gayathriw 

Yes you can do that, you can get a reference to the dom instance that you can work with directly:

https://serp-spider.github.io/documentation/search-engine/google/parse-page/#manipulate-the-dom-object

**Comment by jayparker14** [comment]
Hi @gsouf, I think @gayathriw (as well as myself) wants to do it the other way around:

1) We have already saved `file.html` several days ago.
2) How do we recreate a $response object from `file.html` ?

Ideally we would need something like `$response = $googleClient->readfile('file.html')`

Can we do this?

**Comment by gsouf** [comment]
Hi @jayparker14 

Technically we are not going to deal with a response object, but with a GoogleSerp object. The response object is the output from the network with raw http headers, http body, etc... and the GoogleSerp object is what you will use to parse the dom (the http body from the response).

The good news is that you can do it by yourself as [what is done internally in google client](https://github.com/serp-spider/search-engine-google/blob/v0.1.3/src/GoogleClient.php#L102) with the dom grabbed from the network. The only difference is that you will get the dom from a file. See how you can do that:

```php
use Serps\SearchEngine\Google\GoogleUrl;
use Serps\SearchEngine\Google\Page\GoogleSerp;

// First you need to create a base url that will serve as a base to resolve relative urls from the dom
// Idealy that should be the url that you used to get the page you saved in the file
$url = GoogleUrl::fromString('https://google.com/?q=your+keywords');

$fileContent = file_get_contents('file.html');

// Create a serp with the file content and the url
$serp = new GoogleSerp($fileContent, $url);

// and analyse it
$naturalResults = $serp->getNaturalResults();
```

**Comment by jayparker14** [comment]
@gsouf Thank you very much! We will try this out.
