### ISSUE TITLE
News section (top stories)  is not picked up

### ISSUE THREAD

**Issue by lmahesh5** [serp-spider/search-engine-google#54]
@gsouf Google is using now "Top Stories" section to show news apart from the earlier way of showing news section in search results. This Top Stories is not getting parsed.
Can you include this "Top Stories" also under news results.
Given example below : 
https://www.google.co.in/search?safe=off&site=&source=hp&q=india&oq=india&gs_l=hp.3...380.705.0.866.6.5.0.0.0.0.232.232.2-1.1.0....0...1.1.64.hp..5.0.0.0.hLCgKAmWxZc

**Comment by gsouf** [comment]
Hi @lmahesh5 
Sure I ll do that. You're thinking it can be included as a "in the news" results, aren't you? Because it's slightly different from "in the news". The reason is that "in the news" were from top to bottom and top stories is "left to right", the reason I ask is that it might make a difference in the way it's interpreted from the end user of the library (you in this case) and I'm thinking of how to manage this in versioning.

It's not a bc break, but still it's noticeable enough. That's why I wonder if it would be good to make an major version upgrade when this kind of change happen. I have to think a few on how to manage this because it's important to keep a good flow in semantic versioning.

**Comment by lmahesh5** [comment]
Hi @gsouf 
I was thinking google must be trying to replace the "News" section with this "Top Stories".
Nowadays i see the old news format very rarely and the news links are coming in Top stories section.
Earlier i have attached the Left to Right sample of "Top Stories"
Here one more example for Top Stories for Top to Bottom links : 
https://www.google.com/search?q=latest+news&oq=latest+news&aqs=chrome..69i57j69i61l3j69i60l2.1755j0j7&sourceid=chrome&ie=UTF-8#q=taj+mahal&*

**Comment by gsouf** [comment]
Yes I think google will eventually drop"in the news" as well.

About the last link you sent I only have left to right version of top stories:

![topstories](https://cloud.githubusercontent.com/assets/3215399/24452517/f242cba6-1483-11e7-8443-b426cd35d9f3.png)
 I'll try to search for more of them but if you can send the html you have on your side that would be very helpful

**Comment by lmahesh5** [comment]
Hi @gsouf 
This is the vertical section which i am seeing in the second link.
![topstories](https://cloud.githubusercontent.com/assets/12859259/24453014/c3d86d28-14a3-11e7-9096-8ef8b12360de.jpg)
Also attached the HTML part of it.

[search taj mahal.zip](https://github.com/serp-spider/search-engine-google/files/878893/search.taj.mahal.zip)

**Comment by gsouf** [comment]
@lmahesh5 how often do you encounter vertical top stories list? I searched a lot and never found any of them, I wonder if they are prototype at the moment

**Comment by gsouf** [comment]
@lmahesh5 I have implemented **top stories** in the branch 0.1.x (use dev-0.1.x in composer). 

I'm waiting for your output for my previous question to know if I will also include vertical top stories

**Comment by lmahesh5** [comment]
@gsouf 
Even i am not able to replicate the vertical top stories.
If i get any in future, then will let you know.

**Comment by gsouf** [comment]
Published in version 0.1.4

Documentation is not online yet

**Comment by gsouf** [comment]
Doc available in http://serp-spider.github.io/documentation/search-engine/google/parse-page/#top-stories

**Comment by gsouf** [comment]
I open again because it looks like that news carousel item are not carousel anymore and are not parsed correctly.

**Comment by gsouf** [comment]
The issue was on my side, I gave more tests and eveyrhting is ok.
