### ISSUE TITLE
Dublicates in search results.

### ISSUE THREAD

**Issue by Nix-id** [serp-spider/search-engine-google#55]
Have a problem.
I try parse 10 page for one keyword.
And its contains dublicates urls  on different position
(1-5 urls from 10 pages)

I use ArrayCookieJar  on request
But when i request every next page for keyword Google return new values for cookies.

Why i see dublicates in results?

**Comment by gsouf** [comment]
Hi @Nix-id can you give me a simple example of your code that can help me to reproduce the issue please? 

Also did you check the expected results on your actual browser?

**Comment by gsouf** [comment]
@Nix-id if you dont answer I would consider this issue as fixed. Can you confirm me if it's ok on your side?

**Comment by gsouf** [comment]
@Nix-id I'm closing this issue, feel free to open it again if you still have problems with results
