### ISSUE TITLE
Natural results parsing fails

### ISSUE THREAD

**Issue by thebennos** [serp-spider/search-engine-google#58]
I have problems to parse natural results. 

`        $results = $response->getNaturalResults();
        foreach($results as $result){
            // parse results
            echo $result->title;
        }`

This is my code. 
The Query is ok,proxy works and other parser are working, (Adword, Number of results). 

Other user reported a small change in 
https://github.com/serp-spider/search-engine-google/issues/56

Maybe this is related. 
I use version 0.1.4.

**Comment by gsouf** [comment]
Hi @thebennos 

Yes it's probably the same issue, the good news is that the fix is coming in the next few hours :)

**Comment by gsouf** [comment]
@thebennos I have pushed a fix for #56 in branch ``v0.1.x``. Please, can you make a test by pointing your composer dependency to ``serps/search-engine-google: v0.1.x-dev``.

If it works it means it was the same issue and I can bump the version.

**Comment by thebennos** [comment]
yeah, now it works.

**Comment by gsouf** [comment]
Good! Thanks for your output.

You can now use the version 0.1.5
