### ISSUE TITLE
Top stories not parsed in google mobile

### ISSUE THREAD

**Issue by lmahesh5** [serp-spider/search-engine-google#67]
Hi @gsouf 
Top stories is not getting parsed in google mobile, whereas it is working in google desktop.
You can try with keyword "narendra modi"
Vertical news is coming, though i am checking for both "in_the_news" and "top_stories", it is not getting parsed. 
Please check.

**Comment by gsouf** [comment]
The doc has been updated, the will be released with the next version: 0.2.2
