### ISSUE TITLE
Fatal error GoogleClient.php 

### ISSUE THREAD

**Issue by Carbone13** [serp-spider/search-engine-google#69]
solved and closed

**Comment by Carbone13** [comment]
<img width="1186" alt="screenshot_74" src="https://cloud.githubusercontent.com/assets/12900195/25947975/e1258bf0-367b-11e7-958b-c305e8293a50.png">

GoogleClient.php on line 33

hello , new issued with this error , could you explain this error ? thank you

**Comment by gsouf** [comment]
Hi,

That's probably because you are using the old creation method with the new version of serps. 

Are you new user of the library, or did you upgrade from an older version of the lib?

**Comment by gsouf** [comment]
I found that some instructions have not been updated on the doc.

Until I fix the doc you can check the good instruction here: http://serp-spider.github.io/documentation/search-engine/google/ (you need to wrap curl client in a browser instance)

If you are upgrading from version 0.1 here are the instructions to upgrade: http://serp-spider.github.io/documentation/about/migration/from-v0_1-to-v0_2/

Let me know if it fixed the issue.

**Comment by Carbone13** [comment]
I'm a new user and I have got lib from here using the composer method

<img width="324" alt="screenshot_75" src="https://cloud.githubusercontent.com/assets/12900195/25949666/7a38fd80-3682-11e7-9543-9ffe5fac5f55.png">

Here's what I've run, is this a new or old version?

**Comment by gsouf** [comment]
0.2.0 is the latest version!

**Comment by gsouf** [comment]
Just a side note. I noticed you installed both of zend-diactoros and guzzle/psr-7 but they do the same thing. You only need one of them, not both (but you wont have any issue if you install both)

**Comment by gsouf** [comment]
Hi @Carbone13 

Please, can you tell me if it fixed your issue?

**Comment by gsouf** [comment]
With no answer, I consider it as fixed.  If you are still facing the issue, feel free to open it again.
