### ISSUE TITLE
set referral address - header setup

### ISSUE THREAD

**Issue by FrancisVarga** [serp-spider/search-engine-google#73]
I don't see a way where i can set the referral URL or in general setup the header's from outside.

**Comment by gsouf** [comment]
Hi @FrancisVarga 

That was recently implemented in phantomjs adapter through custom headers, but I want to propose a global solution that allows to set custom headers and that can be used independently of the http client.

At this moment I can imagine two easy ways of implementing this feature.

Either by proposing a handler on the google client that allows to modify a request before it to be sent:

```php
$googleClient->setRequestHandler(function(RequestInterface $request){
    $request = $request->withHeader('referrer', 'mycustomreferer');
    return $request;
});
```

Or by modifying the browsers default headers:

```php
$browser->addDefaultHeader('referrer', 'mycustomreferer');
```

The first solution is specific to the google client, and the second is global to the library and can profit for future search engine clients.

Not sure yet, but I think I will implement both. Would that fit your requirements?

Anyway that's an easy pick feature, give me a few time thinking whether or not it's a good solution.

**Comment by FrancisVarga** [comment]
I think to add it into the browser via addHeader(key, value); makes sense
and easy to understand.

A function for custom interface most likely is to over complicated hehehe

**Comment by gsouf** [comment]
@FrancisVarga version 0.2.2 of serps/core is released to address this issue. You can find details here: https://serp-spider.github.io/documentation/browser/#setting-default-headers

Feel free to re-open the issue if there is anything wrong with the referrer.

Thanks for opening this issue!
