### ISSUE TITLE
Serps\SearchEngine\Google\Exception\InvalidDOMException

### ISSUE THREAD

**Issue by FrancisVarga** [serp-spider/search-engine-google#74]
@gsouf Does the DOM from google changed?

> [2017-07-26 01:32:37] local.CRITICAL: Serps\SearchEngine\Google\Exception\InvalidDOMException: Unable to check javascript status. Google DOM has possibly changed and an update may be required. in /Users/francisvarga/Projects/NA/Scraply/vendor/serps/search-engine-google/src/Page/GoogleSerp.php:116

**Comment by gsouf** [comment]
@FrancisVarga  I dont have any issue on my side.

Can you give me more details like the http adapter you are using or if you did some operation that could alter the request sent to google or used some custom user agent?  

In addition you can save the google dom in a file and check and open this file in  your browser to see if everything is fine. Here are the instructions for saving the dom to a file https://serp-spider.github.io/documentation/search-engine/google/parse-page/#manipulate-the-dom-object

**Comment by FrancisVarga** [comment]
Hi yeah I'm sending custom user agent but it's mine from my browser one to
one copied.

**Comment by gsouf** [comment]
I could test with the given user agent and I dont have any issue yet.

I encourage you to save the dom in a file as said in my previous message and to open it a browser to check that the page is a correct google page. Once you did if you don't see anything weird you might send the file as an attachment for me to analyse it.

Can you do that please?

**Comment by FrancisVarga** [comment]
@gsouf could there be a problem if i run it via client? I have several workers which running in cli mode to have a faster and async scraping of google.

**Comment by gsouf** [comment]
@FrancisVarga what do you mean by client?

**Comment by FrancisVarga** [comment]
@gsouf Runs in cli mode sapi?

**Comment by gsouf** [comment]
No that should not make any problem. Myself I use the [serps cli tool](https://github.com/serp-spider/serps-cli) to make this kind of test :)

**Comment by FrancisVarga** [comment]
@gsouf i don't get it copy pasted the code and got by "normal" frontend request no poblems but running on CLI  i get the error:

```php
public function devSpiderGoogle($term)
	{
		$searchTerm = $term;

		$gUrl = (new GoogleUrl())->setSearchTerm($searchTerm);
		$gUrl->setResultsPerPage(20);
		$googleCli = $this->getGoogleCli();
		$response = $googleCli->query($gUrl);
		for ($i = 0; $i <= $response->getNumberOfResults(); $i++) {
			$gUrl->setPage($i);
			$this->parseResult($googleCli->query($gUrl)->getNaturalResults());
			if ($i >= $this->pageToScrape) {
				return true;
			}
		}
	}

	private function getGoogleCli()
	{
		$agent = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36';
		return new GoogleClient(new Browser(new CurlClient(), $agent, $this->acceptLang));
	}

	private function parseResult($results)
	{
		/** @var ItemPosition $item */
		foreach ($results as $item) {
			if ($item->is(NaturalResultType::CLASSICAL)) {
				$data = $item->getData();
				$d = SpyderGoogleSearchResult::firstOrCreate([
					'url'         => $data['url'],
					'title'       => $data['title'],
					'description' => $data['description']
				]);
				$d->save();
			}
		}
	}
```

**Comment by gsouf** [comment]
Are you getting the issue in the loop? And are you getting it for every searches you do? Because you are iterating on the number of result as if it was the number of pages.

$response->getNumberOfResults() returns the number of results that google shows on the top of the page you should iterate for i being from 1 to ``$response->getNumberOfResults()/[number of results per page]`` but even in that case this number is not precise, it can be an approximation. 

I think the issue is that you are parsing unexisting pages, and this case has not been covered by the library. Can you check if that could be the reason of the issue please?

**Comment by FrancisVarga** [comment]
Sorry bro to bother you more @gsouf...
 I checked:
https://github.com/serp-spider/serps-cli/blob/master/src/Commande/Google/Search.php#L246

And saw you do:
```$response->javascriptIsEvaluated();```
I did the same and the exception is throwing at that line.

**Comment by FrancisVarga** [comment]
hahahahaha stupid misstake. Thanks! I owe you :)

**Comment by gsouf** [comment]
@FrancisVarga  you're welcome. I will raise an other issue because the error message was not explaining the real problem.
