### ISSUE TITLE
I think is broken right now, right?

### ISSUE THREAD

**Issue by joseraul** [serp-spider/search-engine-google#82]
`Unable to check javascript status. Google DOM has possibly changed and an update may be required.`

I was just checking the example of the documentation

**Comment by gsouf** [comment]
Hi @joseraul 
I cannot reproduce the issue. What example did you try?

In the interim you can also try to run [serps cli](https://github.com/serp-spider/serps-cli) that will run use the library to fetch google. That will help to show if it related to your environment. To use it just run the following:

```sh
composer global require serps/cli
serps google:search "foo"
```

**Comment by joseraul** [comment]
Hi @gsouf 

My mistake (I silly one), it works perfectly well.

Thanks
