### ISSUE TITLE
Google Mobile - Missing results

### ISSUE THREAD

**Issue by vinod-maximizer** [serp-spider/search-engine-google#83]
Searched for "sachin tendulkar", made request for page number 1 with 100 results per page. The function getNaturalResults returned only 27 results.

Here is the result file - https://mondovo-serp.s3.amazonaws.com/2017-11-28/1-1.html

**Comment by gsouf** [comment]
Hi @vinod-maximizer thanks for reporting. Will give a look at it.

**Comment by gsouf** [comment]
Hi @vinod-maximizer I pushed a fix and now the file you sent returns 100 results. That will be published with the next releaase
