### ISSUE TITLE
Raw dom is not supported

### ISSUE THREAD

**Issue by opkiler22789** [serp-spider/search-engine-google#86]
`Raw dom is not supported, please provide an evaluated version of the dom Google DOM has possibly changed and an update may be required.` Please tell me how to solve the problem?

**Comment by gsouf** [comment]
Hi @opkiler22789 

Can you let me know what exact step led to this error? Did you use the parser alone, or did you use the google client?

**Comment by opkiler22789** [comment]
@gsouf cakephp + example (http://serp-spider.github.io/documentation/search-engine/google/)

**Comment by gsouf** [comment]
@opkiler22789 I could not reproduce the issue with the code from the doc. Can you confirm that you didn't change anything from the example?

**Comment by opkiler22789** [comment]
it's strange now everything works

**Comment by opkiler22789** [comment]
@gsouf sorry for disturbing, your library is wonderful! thanks for the help

**Comment by gsouf** [comment]
Ok great, maybe you changed the user agent? That can happen when google thinks your user agent is non-compatible
