### ISSUE TITLE
How to get results past page 1 ?

### ISSUE THREAD

**Issue by LunarDevelopment** [serp-spider/search-engine-google#88]
Hello! 

I've had a look through the docs and the code and I can't find a way of asking the library for results past page 1 - is there existing functionality for this I'm missing? 

I've seen other libraries set an inline sleep() while scraping multiple pages and declare number of pages to get on class instantiation which are basic to implement and guard against abuse,

**Comment by gsouf** [comment]
Hi @LunarDevelopment 

Ofcourse you can change the page you want to request, it's achieved this way for page 2: ``$url->setPage(2)``

Doc is right there: https://serp-spider.github.io/documentation/search-engine/google/google-url/#setpage

**Comment by LunarDevelopment** [comment]
Thankyou for the help, I've got another issue open about getting mobile results, hopefully another trivial request for help..
