### ISSUE TITLE
Answer Box not being detected (Google DOM change)

### ISSUE THREAD

**Issue by IMN-MichaelL** [serp-spider/search-engine-google#90]
It appears that Google may have changed their dom in regards to the answer box result type since they are no longer being detected. It looks like the trouble is here: https://github.com/serp-spider/search-engine-google/blob/master/src/Parser/Evaluated/Rule/Natural/AnswerBox.php#L20 I can no longer find any existence of elements with the class of _Z7 in the dom of search results. In testing the issue was simply resolved by removing that line but I am uncertain if that change will cause other issues.

**Comment by gsouf** [comment]
Hi @IMN-MichaelL 

Thanks for reporting. I just released version [0.2.4](https://github.com/serp-spider/search-engine-google/releases/tag/v0.2.4) that fixes it alongside a few other bugs.

Stay tuned with updates because a new patch for other updates ill come soon
