### ISSUE TITLE
getRealtedSearches dom class changed

### ISSUE THREAD

**Issue by gudix** [serp-spider/search-engine-google#93]
in vendor/serps/search-engine-google/src/Page/GoogleSerp.php with function getRelatedSearches() I get no results anymore. 

The Class for DOM-Element changed from `#brs ._e4b>a` to `#brs .nVcaUb`. 

old: `$items = $this->cssQuery('#brs ._e4b>a');`
new: '`$items = $this->cssQuery('#brs .nVcaUb');`

**Comment by gsouf** [comment]
Hi @gudix 
that's implemented in version 0.4.1 feel free to report if it occurs again

**Comment by gudix** [comment]
great! Thank you
