### ISSUE TITLE
Possible error?

### ISSUE THREAD

**Issue by feralheart** [serp-spider/search-engine-google#99]
I tried to implement it to my BotMan based chatbot and it don't have any results with the test data.

**Comment by feralheart** [comment]
I figured it out. In the example the `User Agent` us not a real `useragentstring`. I deleted it except the Mozzila part and now it's working :)

**Comment by gsouf** [comment]
Hi @feralheart can you let me know what exemple you followed? I will try to make it easier to understand.

Thanks
